name: Build WinMemoryCleaner

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy (develop or release)'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - release

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release

    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Bump minor version tag
        id: bump
        shell: pwsh
        run: |
          git fetch --tags
          $tags = git tag --sort=-creatordate | Where-Object { $_ -match '^[0-9]+\.[0-9]+$' }
          if (-not $tags) {
            $newTag = '1.0'
          } else {
            $parts = ($tags[0]).Split('.')
            $newTag = "{0}.{1}" -f $parts[0], ([int]$parts[1] + 1)
          }
          "new_tag=$newTag" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Restore NuGet packages
        shell: pwsh
        run: nuget restore src\WinMemoryCleaner.sln

      - name: Build solution
        shell: pwsh
        run: msbuild src\WinMemoryCleaner.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Import signing certificate (release only)
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: |
          echo "${{ secrets.SIGNING_CERT }}" | Out-File encoded.txt -Encoding ascii
          certutil -decode encoded.txt cert.pfx
          Remove-Item encoded.txt

      - name: Sign executable (release only)
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: |
          $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe |
            Where-Object { $_.FullName -match '\\x64\\' } |
            Select-Object -First 1 -ExpandProperty FullName
          if (-not $signtool) {
            $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe |
              Where-Object { $_.FullName -match '\\x86\\' } |
              Select-Object -First 1 -ExpandProperty FullName
          }
          if (-not $signtool) {
            Write-Error "signtool.exe not found"
            exit 1
          }
          if (-not (Test-Path cert.pfx)) {
            Write-Error "cert.pfx not found!"
            exit 1
          }
          & $signtool sign `
            /f cert.pfx `
            /p "${{ secrets.SIGNING_PASSWORD }}" `
            /tr http://timestamp.digicert.com `
            /td sha256 /fd sha256 `
            src\bin\Release\WinMemoryCleaner.exe

      - name: Verify signature (release only)
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: |
          $sigInfo = Get-AuthenticodeSignature -FilePath src\bin\Release\WinMemoryCleaner.exe
          Write-Host "Signature status: $($sigInfo.Status)"
          if ($sigInfo.Status -ne 'Valid') {
            Write-Error "Executable is not properly signed! Status: $($sigInfo.Status)"
            exit 1
          }

      - name: Cleanup certificate (release only)
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: Remove-Item cert.pfx

      - name: Zip executable (release only)
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: |
          Compress-Archive -Path src\bin\Release\WinMemoryCleaner.exe -DestinationPath WinMemoryCleaner.zip

      - name: Create and push tag
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built
          path: |
            src\bin\Release\WinMemoryCleaner.exe
            WinMemoryCleaner.zip

  release:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built

      - name: Verify signature of executable (release job)
        shell: pwsh
        run: |
          Write-Host "Verifying code signature of downloaded WinMemoryCleaner.exe..."
          $sigInfo = Get-AuthenticodeSignature -FilePath ./WinMemoryCleaner.exe
          Write-Host "Signature status: $($sigInfo.Status)"
          if ($sigInfo.Status -ne 'Valid') {
            Write-Error "Downloaded executable is not properly signed! Status: $($sigInfo.Status)"
            exit 1
          }

      - name: Draft Release using Release Drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.new_tag }}
          files: |
            ./WinMemoryCleaner.exe
            ./WinMemoryCleaner.zip
          draft: true
          make_latest: true
